"""Weighed Similarity

Revision ID: 954b2f089e43
Revises: 5005d5543feb
Create Date: 2024-05-24 14:01:48.880465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '954b2f089e43'
down_revision: Union[str, None] = '5005d5543feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('related_person_similarity', sa.Column('weighted_similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('related_person_similarity', 'weighted_similarity')
    # ### end Alembic commands ###
